language: php
dist: trusty
sudo: false

php:
  - 5.6

install:
  - wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar

before_script:
  - composer self-update -n
  - composer install

  # Run php builtin server
  - nohup php -S 127.0.0.1:8080 -t web > server.log 2>&1 &

  # Run selenium
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - java -jar selenium-server-standalone-2.44.0.jar > selenium.log 2>&1 &
  - sleep 5


script:
  - bin/behat --profile=travis -vvv
